name: Deploy to Surge when push on master

on:
  push:
    branches:
      - master

jobs:
  build_and_deploy:
    environment: production
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./projet/frontend

    steps:
      - name: Fetch code from repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Deploy code
        run: |
          npm install -g surge
          surge --project ./projet/frontend/dist --domain ${{secrets.SURGE_DOMAIN}} --token ${{secrets.SURGE_TOKEN}}